/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-04-05 16:34:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class info_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/info.css\">\r\n");
      out.write("    <title>Checkout-2</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div class=\"container box-flex\">\r\n");
      out.write("        <a class=\"logo\" href=\"#\">rodrina`<span>s</span></a>\r\n");
      out.write("        <div class=\"right\">\r\n");
      out.write("            <a href=\"cart\"><img src=\"img/ico1.png\" alt=\"\"></a>\r\n");
      out.write("            <a href=\"profile\"><img src=\"img/ico2.png\" style=\"padding-left:30px;\" alt=\"\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"main\">Home</a></li>\r\n");
      out.write("            <li><a href=\"product\">All products</a></li>\r\n");
      out.write("            <li><a href=\"product?gender=1\">Man</a></li>\r\n");
      out.write("            <li><a href=\"product?gender=0\">Women</a></li>\r\n");
      out.write("            <li><a href=\"product?cat=ACCESSORIES\">Accessories</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container content \">\r\n");
      out.write("    <div class=\"shipping \">\r\n");
      out.write("        <h2>Correct the information</h2>\r\n");
      out.write("        <form id=\"correct\">\r\n");
      out.write("            <input type=\"name\"class=\"placeholder\" placeholder=\"Name\">\r\n");
      out.write("            <input type=\"phone\" class=\"placeholder\" placeholder=\"phone\">\r\n");
      out.write("            <input type=\"text\" class=\"placeholder\" placeholder=\"Address\">\r\n");
      out.write("            <input type=\"text\" class=\"placeholder\" placeholder=\"Email\">\r\n");
      out.write("            <input id=\"getreg\" type=\"submit\" value=\"OK\">\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"inf\">\r\n");
      out.write("            <a class=\"logo\" href=\"#\">rodrina`<span>s</span></a> <br>\r\n");
      out.write("            <p>Objectively transition extensive data rather than cross\r\n");
      out.write("                functional solutions. Monotonectally syndicate multidisciplinary\r\n");
      out.write("                materials before go forward benefits. Intrinsicly syndicate an\r\n");
      out.write("                expanded array of processes and cross-unit partnerships.\r\n");
      out.write("                <br><br>\r\n");
      out.write("\r\n");
      out.write("                Efficiently plagiarize 24/365 action items and focused infomediaries. <br>\r\n");
      out.write("                Distinctively seize superior initiatives for wireless technologies.\r\n");
      out.write("                Dynamically optimize.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"inf\">\r\n");
      out.write("            <h6>COMPANY</h6>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\">Shop</a></li>\r\n");
      out.write("                <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"inf\">\r\n");
      out.write("            <h6>INFORMATION</h6>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">How to Buy</a></li>\r\n");
      out.write("                <li><a href=\"#\">How to Sell</a></li>\r\n");
      out.write("                <li><a href=\"#\">Promotion</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"inf\">\r\n");
      out.write("            <h6>SHOP CATEGORY</h6>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">Men</a></li>\r\n");
      out.write("                <li><a href=\"#\">Women</a></li>\r\n");
      out.write("                <li><a href=\"#\">Brows All</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"copyrite\">\r\n");
      out.write("    <div class=\"container box-flex\">\r\n");
      out.write("        <a href=\"#\">Copyrite rodrina</a>\r\n");
      out.write("        <div class=\"right\">\r\n");
      out.write("            <a href=\"#\"><img src=\"img/facebook.png\" alt=\"\"></a>\r\n");
      out.write("            <a href=\"#\"><img src=\"img/pinterest.png\" alt=\"\"></a>\r\n");
      out.write("            <a href=\"#\"><img src=\"img/Google.png\" alt=\"\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
